
module.exports = [
  'Accounting / Finance',
  'Healthcare',
  'Non-Profit / Volunteering',
  'Administrative',
  'Computer / Internet',
  'Pharmaceutical / Bio-tech',
  'Arts / Publishing',
  'Hospitality / Entertainment',
  'Real Estate',
  'Banking / Loans',
  'Human Resources',
  'Restaurant / Food Service',
  'Construction / Facilities',
  'Insurance',
  'Retail',
  'Customer Service',
  'Law Enforcement / Security',
  'Sales',
  'Education / Training',
  'Legal / Paralegal',
  'Telecommunications',
  'Engineering / Architecture',
  'Manufacturing / Mechanical',
  'Transportation / Logistics',
  'Government / Military',
  'Marketing / Advertising',
  'Upper Management / Consulting'
 ];
