// Indeed deactivated job keys:
                 // 'sv2e997pr7k7ryhq7q8y4b37', 'ynr9a8wxjcnkfrskyqqvqyd7', '6vfrr4kudkn8dz4cuwau63gr', 'qjjpmdnpbu5w2qmtq2w3a7ab', 'yg2239csx7v9xcapsew6xrmm',
                 // 'k5gpn7xs8pkj2t5xc3yypygg', '3gxyp6rdbgj4kp2zb5zh8p77', 'nkqw6b69wvhzngnzvev8khf5', 'jnxce3jdcefd6zmnf5ygh4sa',
                 // 'aubzvcvtmv4ugurzss9wbe2c', 'x222kkr293hqa3j5f5ze9g6x', 'jusk7z34b9ebjwbrce72nvbd', '4rgtv6mbevf6g7qqjbp2vtsh',
                 // 'n7ydpbfdhr57pc29etu853aj', 'zjrgexbtmp7n6jzk8m9nshvt', 'bcjzgyy78q8u9xq5hnry9bw3', 'tnpvzq9m4bk99w7ymqea22w8',
                 // 'k9vj9hjkchfdd73vfth75ar4', 'pt826dbgvgmuh4rgr52qttmx', 'aunbba5g5fj3gwyntggqkv3f', '7t3u2322a53m685v24hce4g7'];


module.exports = {
  "version" : 2,
  "query" : "web developer",
  "location" : "miami,fl",
  "dupefilter" : true,
  "highlight" : true,
  "radius" : 50,
  "start" : 1,
  "end" : 25,
  "totalResults" : 263,
  "pageNumber" : 0,
  "results" : [
                {
                    "jobtitle" : "Software Developer Level 2",
                    "company" : "PA Group",
                    "city" : "Coral Gables",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Coral Gables, FL",
                    "source" : "Indeed",
                    "date" : "Tue, 10 Nov 2015 19:20:52 GMT",
                    "snippet" : "Working closely with other <b>developers</b>, analysts, designers and SMEs. Working as part of the Technology team, you will develop new software functionality,...",
                    "url" : "http://www.indeed.com/viewjob?jk=d1063bdf98c6f9e4&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.71978,
                    "longitude" : -80.26373,
                    "jobkey" : "d1063bdf98c6f9e4",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Coral Gables, FL",
                    "formattedRelativeTime" : "4 days ago"
}
,
                {
                    "jobtitle" : "Junior Front-End Developer",
                    "company" : "LaunchCode",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "LaunchCode",
                    "date" : "Tue, 03 Nov 2015 04:05:49 GMT",
                    "snippet" : "Ample experience navigating Photoshop and saving images for the <b>web</b>. We place you with an experienced <b>developer</b> from whom you can learn....",
                    "url" : "http://www.indeed.com/viewjob?jk=1a807de3d5a81974&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "1a807de3d5a81974",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "11 days ago"
}
,
                {
                    "jobtitle" : "Web Developer II",
                    "company" : "Florida International University",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Florida International University",
                    "date" : "Fri, 13 Nov 2015 22:38:36 GMT",
                    "snippet" : "<b>Web</b> project management experience. Uses creativity and innovation to resolve <b>web</b> service challenges, work closely with <b>web</b> content editors, application...",
                    "url" : "http://www.indeed.com/viewjob?jk=b8eb1afe6482a58a&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "b8eb1afe6482a58a",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "1 day ago"
}
,
                {
                    "jobtitle" : "Front End Developer",
                    "company" : "CALLPAL APP",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Indeed",
                    "date" : "Thu, 05 Nov 2015 16:34:59 GMT",
                    "snippet" : "Our team is growing fast and we are seeking for Front End <b>Developers</b> to join the team:. This includes all UI programming in AngularJS as well as all front end...",
                    "url" : "http://www.indeed.com/viewjob?jk=3f59fbe4d502dd38&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.782967,
                    "longitude" : -80.19231,
                    "jobkey" : "3f59fbe4d502dd38",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami, FL 33132",
                    "formattedRelativeTime" : "9 days ago"
}
,
                {
                    "jobtitle" : "Junior Front-End Developer",
                    "company" : "LaunchCode",
                    "city" : "Boca Raton",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Boca Raton, FL",
                    "source" : "LaunchCode",
                    "date" : "Tue, 03 Nov 2015 04:05:44 GMT",
                    "snippet" : "Ample experience navigating Photoshop and saving images for the <b>web</b>. We place you with an experienced <b>developer</b> from whom you can learn....",
                    "url" : "http://www.indeed.com/viewjob?jk=1a7253290290024f&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.357143,
                    "longitude" : -80.08242,
                    "jobkey" : "1a7253290290024f",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Boca Raton, FL",
                    "formattedRelativeTime" : "11 days ago"
}
,
                {
                    "jobtitle" : "JavaScript & PHP Web Developer",
                    "company" : "Original Impressions LLC",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Indeed",
                    "date" : "Fri, 13 Nov 2015 19:01:28 GMT",
                    "snippet" : "You will be working on fun tasks such as building front-end <b>web</b> systems and back-end content systems. Original Impressions is seeking an experienced JavaScript...",
                    "url" : "http://www.indeed.com/viewjob?jk=23f9792913c0044d&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "23f9792913c0044d",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "1 day ago"
}
,
                {
                    "jobtitle" : "Graphic Designer - The Wolfsonian (Miami Beach)",
                    "company" : "Florida International University",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Florida International University",
                    "date" : "Fri, 13 Nov 2015 22:38:58 GMT",
                    "snippet" : "Works with others, such as printers, programmers, <b>developers</b> or other technicians to complete the final product....",
                    "url" : "http://www.indeed.com/viewjob?jk=bac03dfe7488df2a&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "bac03dfe7488df2a",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "1 day ago"
}
,
                {
                    "jobtitle" : "Front End Developer",
                    "company" : "RingCentral, Inc.",
                    "city" : "Boca Raton",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Boca Raton, FL",
                    "source" : "RingCentral, Inc.",
                    "date" : "Mon, 09 Nov 2015 10:41:49 GMT",
                    "snippet" : "3+ years\u2019 experience building world class, public facing <b>web</b> applications. Experience interfacing with <b>Web</b> Services platforms and concepts, RESTful APIs, SOAP,...",
                    "url" : "http://www.indeed.com/viewjob?jk=1fcc6f3e385682d4&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.357143,
                    "longitude" : -80.08242,
                    "jobkey" : "1fcc6f3e385682d4",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Boca Raton, FL",
                    "formattedRelativeTime" : "5 days ago"
}
,
                {
                    "jobtitle" : "Web Engineer/Front End Developer",
                    "company" : "MotionPoint",
                    "city" : "Coconut Creek",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Coconut Creek, FL",
                    "source" : "MotionPoint",
                    "date" : "Tue, 10 Nov 2015 09:57:43 GMT",
                    "snippet" : "<b>Web</b> Engineer / Front End <b>Developer</b>. Understand how the worldwide <b>web</b>, the HTTP protocol, and <b>web</b> sites work. <b>Web</b> development and troubleshooting experience....",
                    "url" : "http://www.indeed.com/viewjob?jk=5ed6c7b3f3555903&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.25,
                    "longitude" : -80.17583,
                    "jobkey" : "5ed6c7b3f3555903",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Coconut Creek, FL",
                    "formattedRelativeTime" : "4 days ago"
}
,
                {
                    "jobtitle" : "Junior Front-End Developer",
                    "company" : "LaunchCode",
                    "city" : "Fort Lauderdale",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Fort Lauderdale, FL",
                    "source" : "LaunchCode",
                    "date" : "Tue, 03 Nov 2015 04:05:43 GMT",
                    "snippet" : "Ample experience navigating Photoshop and saving images for the <b>web</b>. We place you with an experienced <b>developer</b> from whom you can learn....",
                    "url" : "http://www.indeed.com/viewjob?jk=b7e77f9597b106a5&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.120878,
                    "longitude" : -80.14286,
                    "jobkey" : "b7e77f9597b106a5",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Fort Lauderdale, FL",
                    "formattedRelativeTime" : "11 days ago"
}
,
                {
                    "jobtitle" : "Backend Web Developer",
                    "company" : "Crescent Heights",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Indeed",
                    "date" : "Fri, 13 Nov 2015 18:37:22 GMT",
                    "snippet" : "2-5 years as a backend <b>web</b> <b>developer</b>. Work with frontend <b>web</b> <b>developer</b> to ensure UI functions correctly. Setup and maintain Apache <b>web</b> servers....",
                    "url" : "http://www.indeed.com/viewjob?jk=910eedb7d1fe4dec&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "910eedb7d1fe4dec",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "1 day ago"
}
,
                {
                    "jobtitle" : "Web Designer/Developer & Graphic",
                    "company" : "CosmoFrance.net",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Indeed",
                    "date" : "Fri, 06 Nov 2015 16:12:32 GMT",
                    "snippet" : "We're looking for a <b>web</b> &amp; graphic designer to design and/or re-design our product websites, as well as brochures, , email newsletters &amp; other marketing material...",
                    "url" : "http://www.indeed.com/viewjob?jk=efcd23b23e721570&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.782967,
                    "longitude" : -80.19231,
                    "jobkey" : "efcd23b23e721570",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami, FL 33132",
                    "formattedRelativeTime" : "8 days ago"
}
,
                {
                    "jobtitle" : "Full Stack Developer",
                    "company" : "CALLPAL APP",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Indeed",
                    "date" : "Thu, 05 Nov 2015 16:36:00 GMT",
                    "snippet" : "Full Stack <b>Developer</b>*. We are growing fast and we are seeking a full stack <b>developer</b> to help in the creation and maintenance of our various websites....",
                    "url" : "http://www.indeed.com/viewjob?jk=1b93e4db925884d0&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.782967,
                    "longitude" : -80.19231,
                    "jobkey" : "1b93e4db925884d0",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami, FL 33132",
                    "formattedRelativeTime" : "9 days ago"
}
,
                {
                    "jobtitle" : "JavaScript Developer",
                    "company" : "Playwire Media",
                    "city" : "Deerfield Beach",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Deerfield Beach, FL",
                    "source" : "Indeed",
                    "date" : "Fri, 13 Nov 2015 16:30:56 GMT",
                    "snippet" : "Experience with video for the <b>web</b>, particularly HTML5 video. Playwire seeks a Javascript <b>developer</b> to aid in the ongoing development and enhancement of products...",
                    "url" : "http://www.indeed.com/viewjob?jk=68b0502340f8aedf&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.315933,
                    "longitude" : -80.0989,
                    "jobkey" : "68b0502340f8aedf",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Deerfield Beach, FL",
                    "formattedRelativeTime" : "1 day ago"
}
,
                {
                    "jobtitle" : "Web Developer",
                    "company" : "Regis HRG",
                    "city" : "Hialeah",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Hialeah, FL",
                    "source" : "Indeed",
                    "date" : "Tue, 27 Oct 2015 16:26:55 GMT",
                    "snippet" : "You're into <b>web</b> development. One of our clients is hiring a *<b>Web</b> <b>Developer</b>*. You're into <b>web</b> technology and have a decent eye for what looks good....",
                    "url" : "http://www.indeed.com/viewjob?jk=5f254d89720d8322&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.901098,
                    "longitude" : -80.3022,
                    "jobkey" : "5f254d89720d8322",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Hialeah, FL 33014",
                    "formattedRelativeTime" : "18 days ago"
}
,
                {
                    "jobtitle" : "Lead Front-End Developer",
                    "company" : "HYP3R",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "HYP3R",
                    "date" : "Tue, 27 Oct 2015 10:17:33 GMT",
                    "snippet" : "Analyzing and enhancing our <b>web</b> application performance. Experience with responsive and <b>web</b> mobile optimization techniques....",
                    "url" : "http://www.indeed.com/viewjob?jk=79bf5558e5ba9541&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "79bf5558e5ba9541",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "18 days ago"
}
,
                {
                    "jobtitle" : "Junior Java Developer",
                    "company" : "LaunchCode",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "LaunchCode",
                    "date" : "Tue, 03 Nov 2015 04:05:46 GMT",
                    "snippet" : "Some experience in developing <b>web</b> applications using at least one popular <b>web</b> framework (JSF, Wicket, GWT, Spring MVC)....",
                    "url" : "http://www.indeed.com/viewjob?jk=416900b2b766c790&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "416900b2b766c790",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "11 days ago"
}
,
                {
                    "jobtitle" : "Sr. PHP Backend Engineer - Payments",
                    "company" : "Linio",
                    "city" : "Hollywood",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Hollywood, FL",
                    "source" : "Linio",
                    "date" : "Thu, 05 Nov 2015 23:48:40 GMT",
                    "snippet" : "A variety of <b>web</b> technologies, particularly JSON and RESTful APIs. You\u2019ll enjoy working with a team of equally strong <b>developers</b> who value your technical...",
                    "url" : "http://www.indeed.com/viewjob?jk=682fe0a0acb2732a&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.016483,
                    "longitude" : -80.14835,
                    "jobkey" : "682fe0a0acb2732a",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Hollywood, FL 33020",
                    "formattedRelativeTime" : "9 days ago"
}
,
                {
                    "jobtitle" : "Web Master- Software Developer vb vs2013+",
                    "company" : "Boca Raton Regional Hospital",
                    "city" : "Boca Raton",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Boca Raton, FL",
                    "source" : "Boca Raton Regional Hospital",
                    "date" : "Wed, 04 Nov 2015 06:23:00 GMT",
                    "snippet" : "The <b>Web</b> Master-Software <b>Developer</b> is responsible for the Hospital website development, utilizing ASP.NET (vb.net) and MS SQL server....",
                    "url" : "http://www.indeed.com/viewjob?jk=e04169c0bd508484&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.343407,
                    "longitude" : -80.07692,
                    "jobkey" : "e04169c0bd508484",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Boca Raton, FL 33427",
                    "formattedRelativeTime" : "10 days ago"
}
,
                {
                    "jobtitle" : "Front End Web Developer",
                    "company" : "Ikone International",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "Indeed",
                    "date" : "Mon, 19 Oct 2015 00:49:18 GMT",
                    "snippet" : "Front end <b>web</b> <b>developer</b>:. <b>Web</b> <b>developer</b>/programmer (Miami, FL). We are currently looking for an extremely experienced <b>web</b> designer/programmer to fill the...",
                    "url" : "http://www.indeed.com/viewjob?jk=5ff77ef96eb7fe43&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.89011,
                    "longitude" : -80.17583,
                    "jobkey" : "5ff77ef96eb7fe43",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami, FL 33161",
                    "formattedRelativeTime" : "27 days ago"
}
,
                {
                    "jobtitle" : "Junior Java Developer",
                    "company" : "LaunchCode",
                    "city" : "Boca Raton",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Boca Raton, FL",
                    "source" : "LaunchCode",
                    "date" : "Tue, 03 Nov 2015 04:05:46 GMT",
                    "snippet" : "Some experience in developing <b>web</b> applications using at least one popular <b>web</b> framework (JSF, Wicket, GWT, Spring MVC)....",
                    "url" : "http://www.indeed.com/viewjob?jk=ab0ed7d6f7f5ef43&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.357143,
                    "longitude" : -80.08242,
                    "jobkey" : "ab0ed7d6f7f5ef43",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Boca Raton, FL",
                    "formattedRelativeTime" : "11 days ago"
}
,
                {
                    "jobtitle" : "Full Stack Rails Developer",
                    "company" : "Playwire Media",
                    "city" : "Deerfield Beach",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Deerfield Beach, FL",
                    "source" : "Indeed",
                    "date" : "Wed, 28 Oct 2015 19:31:49 GMT",
                    "snippet" : "Full Stack Rails <b>Developer</b>:. Experience with video for the <b>web</b>, particularly HTML5 video. Playwire Media seeks a Ruby on Rails <b>developer</b> to help build new...",
                    "url" : "http://www.indeed.com/viewjob?jk=8b06f3227247c5df&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.315933,
                    "longitude" : -80.0989,
                    "jobkey" : "8b06f3227247c5df",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Deerfield Beach, FL",
                    "formattedRelativeTime" : "17 days ago"
}
,
                {
                    "jobtitle" : "Front End Web Developer - Javascript, HTML, CSS, jQuery",
                    "company" : "3dcart Shopping Cart Software",
                    "city" : "Tamarac",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Tamarac, FL",
                    "source" : "3DCart Shopping Cart Software",
                    "date" : "Wed, 21 Oct 2015 18:06:17 GMT",
                    "snippet" : "Front End <b>Web</b> <b>Developer</b> - Javascript, HTML, CSS, jQuery. The <b>Web</b> <b>Developer</b> must be willing to work additional hours to meet deadlines....",
                    "url" : "http://www.indeed.com/viewjob?jk=4379f533d49c7e5e&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 26.211538,
                    "longitude" : -80.24725,
                    "jobkey" : "4379f533d49c7e5e",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Tamarac, FL",
                    "formattedRelativeTime" : "24 days ago"
}
,
                {
                    "jobtitle" : "Front End Developer",
                    "company" : "AdMobilize",
                    "city" : "Miami Beach",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami Beach, FL",
                    "source" : "Indeed",
                    "date" : "Mon, 12 Oct 2015 20:30:15 GMT",
                    "snippet" : "Experience with Bootstrap, React and familiar with <b>web</b> components. Work cross-functionally with designers, strategists and engineers to conceptualize, design,...",
                    "url" : "http://www.indeed.com/viewjob?jk=151e4c448780ec40&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.788462,
                    "longitude" : -80.12637,
                    "jobkey" : "151e4c448780ec40",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : true,
                    "formattedLocationFull" : "Miami Beach, FL",
                    "formattedRelativeTime" : "30+ days ago"
}
,
                {
                    "jobtitle" : "Entry Level Developer",
                    "company" : "LaunchCode",
                    "city" : "Miami",
                    "state" : "FL",
                    "country" : "US",
                    "formattedLocation" : "Miami, FL",
                    "source" : "LaunchCode",
                    "date" : "Sat, 10 Oct 2015 03:05:18 GMT",
                    "snippet" : "We place you with an experienced <b>developer</b> from whom you can learn. Don't have a CS degree?...",
                    "url" : "http://www.indeed.com/viewjob?jk=6d9f6d213ddf08bb&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPfjPDrmo68-trmzJijLNUTeBoNH4tJUazwOak_lJrtn7Qkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a44huoib18kt6ss",
                    "onmousedown" : "indeed_clk(this, '412');",
                    "latitude" : 25.771978,
                    "longitude" : -80.19231,
                    "jobkey" : "6d9f6d213ddf08bb",
                    "sponsored" : false,
                    "expired" : false,
                    "indeedApply" : false,
                    "formattedLocationFull" : "Miami, FL",
                    "formattedRelativeTime" : "30+ days ago"
}
  ]
};